---
title: "Grooming Scenarios"
author: "Anna Willoughby"
date: "2025-05-22"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr) 
library(ggplot2)
library(dplyr)
library(gridExtra) # plotting multipanels 
```

```{r single scenarios}
# Define parasite density range
x <- seq(0.01, 100, length.out = 1000)

# Define grooming scenarios 

## no grooming 
death_none <- function(x) rep(0, length(x))

## programmed to a certain number of fleas per day (G)
death_programmed <-  function(x, G = 10) {
  pmin(1, G / x)  # cap at 1 to avoid unrealistic death rates > 1
} 

## saturate to a % of fleas (e.g., stimulus driven) perG
death_stimulus <- function(x, d0 = 0, dmax = 1, perG  = 0.75) {
  k <- x * (1 - perG) / perG
  d0 + (dmax * x) / (k + x)
}

## costly, stimulus driven to a certain point, but then there is a cost 
# death_costly <- function(x, max = 1, mu = 10, sigma = 10) {
#  max * exp(-((x - mu)^2) / (2 * sigma^2))
#}

# Evaluate each function
df <- data.frame(
  x = x,
  none = death_none(x),
  programmed = death_programmed(x),
  stimulus = death_stimulus(x)#,
  #costly = death_costly(x)
)


df_long <- pivot_longer(df, -x, names_to = "grooming scenario", values_to = "DeathRate")

# Plot
## Facet plot of grooming scenarios 
ggplot(df_long, aes(x = x, y = DeathRate, group =  `grooming scenario`, color = `grooming scenario`)) +
  geom_line(size = 1.2) +
  facet_wrap(~factor(`grooming scenario`, levels = c("none", "programmed", "stimulus", "costly")))  +
  labs(
    x = "ectoparasite population size",
    y = expression(mu)
  ) +
  theme_minimal() +
  scale_color_brewer(palette = "Dark2") + 
  theme(legend.position = "none")

## Merge plot of grooming scenarios 
  
```

```{r}
# plot different grooming scenarios 

# 1. Define parameter ranges
x_vals <- seq(1, 100, length.out = 100)  # parasite population size 
G_vals <- seq(0, 100, length.out = 101)   # grooming efficiency
plot_scenarios <- c(1,10,20,30,40,50,60,70,80,90,100)

# 2. Create a grid of all combinations
grid_prog <- expand.grid(
  pop_size = x_vals,
  groom_efficiency = G_vals
)

# Provide some columns for 
## scenario 
grid_prog$scenario <- grid_prog$groom_efficiency

# Programmed: can remove up to G fleas per day
grid_prog$fleas_groomed <- pmin(grid_prog$pop_size, grid_prog$groom_efficiency)
grid_prog$death_rate <- grid_prog$fleas_groomed 

# PROGRAMMED
## Plot full parameter space for Programmed 
ggplot(grid_prog, aes(x = pop_size, y = groom_efficiency, fill = death_rate)) +
  geom_tile() +
  scale_fill_viridis_c(option = "inferno", direction = -1) +
  labs(
    x = "ectoparasite population size",
    y = "programmed groom limit",
    fill = "mortality rate"
  ) +
  theme_classic()

## PROGRAMMED
# Plot example for all grooming efficiency scenarios 
prog_scenarios <- ggplot(grid_prog[grid_prog$scenario %in% plot_scenarios, ], aes(x = pop_size, y = death_rate, 
                      group = groom_efficiency, color = fleas_groomed)) +
  geom_line() +
  scale_color_gradientn(
    colours = c("gray70", viridis::viridis(255, option = "inferno", direction = -1)),
    values  = scales::rescale(c(0, 100)),
    limits  = c(0, 100),
    breaks  = c(0, 25, 50, 75, 100),
  ) +
  labs(
    x = "ectoparasite population size",
    y = "death rate (ectoparasites groomed per day)",
    title = expression(bold("a.") ~ " Programmed")
  ) +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.1,vjust = -10))
prog_scenarios # check all good

## make a no legend version for multi-panel
prog_scenarios_nl <- prog_scenarios + 
  theme(legend.position = "none")


# Stimulus-driven: can remove up to %perG per day 
stim_rates <- seq(0, 1, length.out = 101)  # death rates (for stimulus)

grid_stim <- expand.grid(
  pop_size = x_vals,
  stim_rate = stim_rates
)
grid_stim$scenario <- as.integer(factor(grid_stim$stim_rate))
grid_stim$fleas_groomed <- grid_stim$pop_size*grid_stim$stim_rate

## Plot full parameter space for Stimulus
ggplot(grid_stim, aes(x = pop_size, y = fleas_groomed, fill = stim_rate)) +
  geom_tile() +
  scale_fill_viridis_c(option = "inferno", direction = -1) +
  labs(
    x = "ectoparasite population size",
    y = "grooming efficiency",
    fill = "mortality rate"
  ) +
  theme_classic()

stim_scenarios <- ggplot(grid_stim[grid_stim$scenario %in%  plot_scenarios, ], aes(x = pop_size, y = fleas_groomed, 
                      group = stim_rate, color =  fleas_groomed)) +
  geom_line() +
  scale_color_gradientn(
    colours = c("gray70", viridis::viridis(255, option = "inferno", direction = -1)),
    values  = scales::rescale(c(0, 100)),
    limits  = c(0, 100),
    breaks  = c(0, 25, 50, 75, 100),
    name    = "Ectoparasite Deaths"
  ) +
  labs(
    x = "ectoparasite population size",
    y = "death rate",
    title = expression(bold("b.") ~ " Stimulus-driven")
  ) +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.1,vjust = -10))
stim_scenarios # check all good 

## make a no legend version for multi-panel
stim_scenarios_nl_ny <- stim_scenarios + 
  theme(legend.position = "none", 
        axis.title.y = element_blank(),
        axis.text.y  = element_blank(),
        axis.ticks.y = element_blank())

# Costly: Gaussian centered at a variable peak/optimal ectoparasite that then decreases 

## explore 100 different scenarios of cost
n_scen <- 100

# parameter trajectories
cost_scenarios <- data.frame(
  scenario = 1:n_scen,
  mu = seq(10, 80, length.out = n_scen),
  sigma = seq(2, 20, length.out = n_scen)
)

grid_cost  <- expand_grid(
  pop_size = 1:100, # ectoparasite population size
  scenario = 1:100 # this changes the type of gaussian curve
) 

grid_cost <- left_join(grid_cost, cost_scenarios, by = "scenario")
grid_cost$death_rate <- exp(-((grid_cost$pop_size - grid_cost$mu)^2) / (2 * grid_cost$sigma^2))
grid_cost$fleas_groomed <- floor(grid_cost$pop_size*grid_cost$death_rate)


cost_scenarios <- ggplot(grid_cost[grid_cost$scenario %in%  plot_scenarios, ], 
                         aes(x = pop_size, y = fleas_groomed, 
                      group = scenario, color =  fleas_groomed)) +
  geom_line() +
  scale_color_gradientn(
    colours = c("gray70", viridis::viridis(255, option = "inferno", direction = -1)),
    values  = scales::rescale(c(0, 100)),
    limits  = c(0, 100),
    breaks  = c(0, 25, 50, 75, 100),
    name    = "host effort") +
  labs(
    x = "ectoparasite population size",
    y = "death rate",
   title = expression(bold("c.") ~ " Costly")) +
  theme_classic() +
  theme(legend.position = c(0.98, 0.98),
        legend.justification = c(1, 1), 
        legend.background = element_rect(fill = NA, color = NA),
        legend.box.background = element_rect(fill = NA, color = NA), 
        legend.text  = element_text(size = 6),
        legend.title = element_text(size = 7), 
        plot.title = element_text(hjust = 0.1,vjust = -10))+ 
  guides(
  color = guide_colorbar(
    title.position = "top",
    title.hjust = 1, 
    barheight = unit(0.8, "in"),
    barwidth  = unit(0.2, "in"),
    ticks = FALSE))
cost_scenarios # check all good 

# remove y axis for multipanel
cost_scenarios_ny <- cost_scenarios + 
  theme(axis.title.y = element_blank(),
  axis.text.y  = element_blank(),
  axis.ticks.y = element_blank())

# plot all three scenarios next to eachother 
png(filename="figures/groom_scenarios.png", width = 7.5, height =3, unit = 'in', res = 300)
grid.arrange(prog_scenarios_nl, stim_scenarios_nl_ny, nrow = 1)
dev.off()
```

```{r plot with resources }
prog_scenarios_Res <- ggplot(grid_prog[grid_prog$scenario %in% plot_scenarios, ], 
                         aes(x = pop_size, y = death_rate, 
                      group = groom_efficiency, color = scenario)) +
  geom_line() +
  scale_color_gradientn(
    colours = c("gray70", viridis::viridis(255, option = "inferno", direction = -1)),
    values  = scales::rescale(c(0, 100)),
    limits  = c(0, 100),
    breaks  = c(0, 50, 100),
    labels = c("Low","Mid","High"), 
    name = expression(bold("Resources")),
    guide = guide_colorbar(
      barheight = unit(0.4, "in"))) +   # shorter legend
  labs(
    x = "ectoparasite population size",
    y = "death rate (fleas groomed per day)",
    title = expression(bold("a.") ~ " Programmed")
  ) +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.1,vjust = -10), 
        legend.position = c(0.4, 0.8),
        legend.justification = c(1, 1), 
        legend.background = element_rect(fill = NA, color = "black"),
        legend.box.background = element_rect(fill = NA, color = NA), 
        legend.text  = element_text(size = 6),
        legend.title = element_text(size = 7)
        )
prog_scenarios_Res # check all good

## make a no legend version for multi-panel
prog_scenarios_Res_nl <- prog_scenarios_Res + 
  theme(legend.position = "none")


stim_scenarios_Res <- ggplot(grid_stim[grid_stim$scenario %in%  plot_scenarios, ], aes(x = pop_size, y = fleas_groomed, 
                      group = stim_rate, color =  scenario)) +
  geom_line() +
  scale_color_gradientn(
    colours = c("gray70", viridis::viridis(255, option = "inferno", direction = -1)),
    values  = scales::rescale(c(0, 100)),
    limits  = c(0, 100),
    breaks  = c(0, 25, 50, 75, 100),
    name    = "Ectoparasite Deaths"
  ) +
  labs(
    x = "ectoparasite population size",
    y = "death rate",
    title = expression(bold("b.") ~ " Stimulus-driven")
  ) +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.1,vjust = -10))
stim_scenarios_Res # check all good 

## make a no legend version for multi-panel
stim_scenarios_Res_nl_ny <- stim_scenarios_Res + 
  theme(legend.position = "none", 
        axis.title.y = element_blank(),
        axis.text.y  = element_blank(),
        axis.ticks.y = element_blank())

# Costly: Gaussian centered at a variable peak/optimal ectoparasite that then decreases 

cost_scenarios_Res <- ggplot(grid_cost[grid_cost$scenario %in%  plot_scenarios, ], 
                         aes(x = pop_size, y = fleas_groomed, 
                      group = scenario, color =  mu)) +
  geom_line() +
  scale_color_gradientn(
    colours = c("gray70", viridis::viridis(255, option = "inferno", direction = -1)),
    values  = scales::rescale(c(0, 100)),
    limits  = c(1, 80),
    breaks  = c(1, 80),
    labels = c("Low","High"), 
    name    = "Resources") +
  labs(
    x = "ectoparasite population size",
    y = "death rate",
   title = expression(bold("c.") ~ " Costly")) +
  theme_classic() +
  theme(legend.position = c(1, 1.1),
        legend.justification = c(1, 1), 
        legend.background = element_rect(fill = NA, color = NA),
        legend.box.background = element_rect(fill = NA, color = NA), 
        legend.text  = element_text(size = 6),
        legend.title = element_text(size = 7), 
        plot.title = element_text(hjust = 0.1,vjust = -10))+ 
  guides(
  color = guide_colorbar(
    title.position = "top",
    title.hjust = 1, 
    barheight = unit(0.8, "in"),
    barwidth  = unit(0.2, "in"),
    ticks = FALSE))
cost_scenarios_Res # check all good 

# remove y axis for multipanel
cost_scenarios_Res_ny_nl <- cost_scenarios_Res + 
  theme(axis.title.y = element_blank(),
  axis.text.y  = element_blank(),
  axis.ticks.y = element_blank(), 
  legend.position = "none")

# plot all three scenarios next to eachother 
png(filename="figures/groom_scenarios2.png", width = 7.5, height =3, unit = 'in', res = 300)
grid.arrange(prog_scenarios_Res, stim_scenarios_Res_nl_ny, #cost_scenarios_Res_ny_nl,
             nrow = 1)
dev.off()
```
```{r plot full growth formula}
## DEFINE FUNCTIONS 
# function for birth rate with Allee effect (theta)
birthrate <- function(x, b0, theta, K){
  b <- b0*x*(x/(theta+x)) # baseline births with Allee
  b_dd <- b*x*(1 - x/ K) # birth decreases at high densities
  b_wA_dd <- pmax(0, b_dd)
  b_wA_dd # birth rate with Allee and density dependence
}

immigrationrate <- function (x, iota) iota # function for immigration rate (iota)

# read in all the death rates 

## Define all Grooming Scenarios: 
### PROGRAMMED 
groom_prg_scenarios <- data.frame(scenario = seq(1, 100, length.out = 100), # 100 scenarios 
                                  G_vals = seq(1, 100, length.out = 100)) # grooming efficiency
#### Generate a function for grooming deathrate based on pop size 
groomrate_prg <- function(pop.size, scenario_id){
  death_rate <- pmin(pop.size, scenario_id)
  death_rate
}
### STIMULUS
groom_stm_scenarios <- data.frame(scenario = seq(1, 100, length.out = 100), # 100 scenarios 
                                  G_vals = seq(1, 100, length.out = 100)) # grooming efficiency
groom_stm_scenarios$groom_rate <- groom_stm_scenarios$G_vals / 100
  
#### Generate a function for stimulus grooming deathrate based on pop size 
groomrate_stm <- function(pop.size, scenario_id){
  death_rate <- ifelse(pop.size == 0, 0, # avoids NaNs
                       pop.size*groom_stm_scenarios[scenario_id,3])
  death_rate
}

### Costly
n_scen <-  100
# max grooming of 80 per day 
groom_cst_scenarios <- data.frame(
  scenario = 1:n_scen,
  mu = seq(10, 80, length.out = n_scen),
  sigma = seq(2, 20, length.out = n_scen)
) # max var of 20 sigma

#### Generate a function for costly grooming deathrate based on pop size 
groomrate_cst <- function(pop.size, scenario){
  groom_cst_scenario <- groom_cst_scenarios %>% dplyr::filter(scenario == scenario) # filter to scenario 
  death_rate <- ifelse(pop.size == 0, 0, # avoids NaNs
                       pop.size*exp(-((pop.size - groom_cst_scenario$mu)^2) / 
                                      (2 * groom_cst_scenario$sigma^2))) # normal distribution
  death_rate
}

# Function to select a groom strategy based on defined parameter: 
get_groom_rate <- function(pop.size, groom_strategy, scenario) {
  if (groom_strategy == "none") {
    return(0)
  } else if (groom_strategy == "programmed") {
    return(groomrate_prg(pop.size, scenario))
  } else if (groom_strategy == "stimulus") {
    return(groomrate_stm(pop.size, scenario))
  }
}

# Function for density dependent deaths 
deathrate_dd <- function(pop.size, dmax = 1, x_mid = 50, s = 20) {
     dmax / (1 + exp(-(pop.size - x_mid) / s))
}

# set initial conditions parameters

## birth rate is standard across all scenarios, right now as 37.5 flea births per year (0. per day)
## we are going to vary parameters for:  
theta_vals <- seq(0, 10, by = 1) # 10 different values
iota_vals <- seq(0, 0.5, by = 0.05) # 10 different values
scenario_vals <- seq(1,100, by = 1) # 100 different values (no grooming is an explicit scenario) 

# construct full matrix of theta and iota options 
ti_axes <- expand.grid(
  theta = theta_vals, 
  iota = iota_vals, 
  scenario = scenario_vals
)

# Expand parameter set to include each grooming scenario 
groom_strategies <- c("none", "programmed", "stimulus")
tig_axes <- merge(ti_axes,
                  data.frame(groom_strategy = groom_strategies),
                             by = NULL)

# Construct parameter set
param_grid <- tig_axes
param_grid$b0 <- log(78.75)/89/2 # constant [log(female fecundity per lifetime)/generation time]
param_grid$initial_pop <- 1

# DEFINE DATA FRAME 
ecto.pop.rates <- tig_axes

gr1 <- vector("list", nrow(ecto.pop.rates))

# calculate growth rate for each parameter combo for pop sizes 1:100
system.time({
for (i in seq_len(nrow(ecto.pop.rates))) {
  
  row.params <- as.list(ecto.pop.rates[i, ])
  
  x_vals <- 1:100
  
  gr1[[i]] <- birthrate(x_vals, log(78.75)/89, row.params$theta, 50) -
    deathrate_dd(x_vals) -
    get_groom_rate(x_vals, row.params$groom_strategy, row.params$scenario) +
    immigrationrate(x_vals, row.params$iota)
}
  })

# create a data frame 
ecto.pop.rates_long <- ecto.pop.rates %>%
  mutate(gr = gr1) %>%
  unnest(gr) %>%
  mutate(pop.size = rep(1:100, times = nrow(ecto.pop.rates)))

# plot ecto pop rates (epr) by pop size 
ecto.pop.rates_long$groom_strategy <- factor(ecto.pop.rates_long$groom_strategy, levels = c("none", "programmed", "stimulus"))

epr_plot <- ggplot(ecto.pop.rates_long[ecto.pop.rates_long$theta == 6 &
                                       ecto.pop.rates_long$iota == 0.5,], 
                         aes(x = pop.size, y = gr, 
                             group = scenario, color = scenario)) +
  geom_line(size = 1) +
  facet_wrap(~groom_strategy) +
  #scale_y_continuous(limits = c(-2,8)) +
  geom_hline(yintercept=0, color = "black") +
   scale_color_gradientn(
    colours = c("gray70", viridis::viridis(255, option = "inferno", direction = -1)),
    values  = scales::rescale(c(1, 100)),
    limits  = c(1, 100),
    breaks  = c(1, 100),
    labels = c("Low","High"), 
    name    = "Resources") +
  labs(
    x = "ectoparasite population size",
    y = "growth rate",
   # title = expression(bold("a.") ~ " Programmed")
  ) +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.1,vjust = -10), 
        legend.position = c(0.1, 0.4),
        legend.justification = c(1, 1), 
        legend.background = element_rect(fill = NA, color = "black"),
        legend.box.background = element_rect(fill = NA, color = NA), 
        legend.text  = element_text(size = 6),
        legend.title = element_text(size = 7)
        )
epr_plot 

png(filename="figures/growth_rate_by_mgroom_t6i05.png", width = 7.5, height =3, unit = 'in', res = 300)

grid.arrange(prog_scenarios_Res, stim_scenarios_Res_nl_ny, #cost_scenarios_Res_ny_nl,
             epr_plot, nrow = 2, ncol = 2)
dev.off()

```

```{r immigration and grooming resources }
immigrationrate <- function(x, iota_baseline, scenario_id){
  r_scaled <- scenario_id / 100
  iota_baseline + exp(2 * r_scaled)
}

# DEFINE DATA FRAME 
ecto.pop.rates_wi <- tig_axes
ecto.pop.rates_wi$iota = 0.02

gr1_wi <- vector("list", nrow(ecto.pop.rates_wi))

system.time({
for (i in seq_len(nrow(ecto.pop.rates_wi))) {
  
  row.params <- as.list(ecto.pop.rates_wi[i, ])
  
  x_vals <- 1:100
  
  gr1_wi[[i]] <- birthrate(x_vals, log(78.75)/89, row.params$theta, 50) -
    deathrate_dd(x_vals) -
    get_groom_rate(x_vals, row.params$groom_strategy, row.params$scenario) +
    immigrationrate(x_vals, row.params$iota, row.params$scenario)
}
  })

# create a data frame 
ecto.pop.rates_wi_long <- ecto.pop.rates_wi %>%
  mutate(gr = gr1_wi) %>%
  unnest(gr) %>%
  mutate(pop.size = rep(1:100, times = nrow(ecto.pop.rates_wi)))

# plot ecto pop rates (epr) by pop size 
ecto.pop.rates_wi_long$groom_strategy <- factor(ecto.pop.rates_wi_long$groom_strategy, levels = c("none", "programmed", "stimulus"))

epr_plot_wi <- ggplot(ecto.pop.rates_wi_long[ecto.pop.rates_wi_long$theta == 6,], 
                         aes(x = pop.size, y = gr, 
                             group = scenario, color = scenario)) +
  geom_line(size = 1) +
  facet_wrap(~groom_strategy) +
  scale_y_continuous(limits = c(-100,30)) +
  geom_hline(yintercept=0, color = "black") +
   scale_color_gradientn(
    colours = c("gray70", viridis::viridis(255, option = "inferno", direction = -1)),
    values  = scales::rescale(c(1, 100)),
    limits  = c(1, 100),
    breaks  = c(1, 100),
    labels = c("Low","High"), 
    name    = "Resources") +
  labs(
    x = "ectoparasite population size",
    y = "growth rate",
   # title = expression(bold("a.") ~ " Programmed")
  ) +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.1,vjust = -10), 
        legend.position = c(0.1, 0.4),
        legend.justification = c(1, 1), 
        legend.background = element_rect(fill = NA, color = "black"),
        legend.box.background = element_rect(fill = NA, color = NA), 
        legend.text  = element_text(size = 6),
        legend.title = element_text(size = 7)
        )


png(filename="figures/growth_rate_by_rg_ri_t6.png", width = 7.5, height =3, unit = 'in', res = 300)
epr_plot_wi 
dev.off()


```
